# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#6C63FF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[server]
enableXsrfProtection = false
headless = true
